-- 코드를 입력하세요
SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    sum(FP.PRICE * FO.AMOUNT) as TOTAL_SALES
FROM 
    FOOD_PRODUCT FP
LEFT JOIN FOOD_ORDER FO ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE
    FO.PRODUCE_DATE like '%2022-05%'
GROUP BY 
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    FP.PRODUCT_ID ASC;
 